### ISSUE TITLE
Add Velocity plugin logo

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-apache-velocity#2]
Logo from Wikipedia (non-square, with text): https://upload.wikimedia.org/wikipedia/commons/c/cb/Apache_Velocity_logo.svg
Edited square SVG with logo only: [Apache_Velocity_logo.zip](https://github.com/consulo/consulo-apache-velocity/files/7468338/Apache_Velocity_logo.zip)
![изображение](https://user-images.githubusercontent.com/16825982/140081288-26d0160c-e85d-4fd4-93b5-20493f13f2b7.png)

**Comment by unv-unv** [comment]
Optimized SVG: [Apache_Velocity_logo.zip](https://github.com/consulo/consulo-apache-velocity/files/7468431/Apache_Velocity_logo.zip)

**Comment by VISTALL** [comment]
Hello. Optimized icon good - but idk why svg contains useless metadata tag. And why size in **mm**? export options? (better in pixels)

**Comment by unv-unv** [comment]
[Apache_Velocity_logo.zip](https://github.com/consulo/consulo-apache-velocity/files/7469526/Apache_Velocity_logo.zip)
I've found how to change size into pixels and found how to export without metadata.
